STRINGS = {
    'ar': {
        'start': '✨ مرحباً بك في <b>StickerForgeBot</b>!\n\nأنا بوت إنشاء ملصقات تيليجرام الاحترافي.\nأرسل لي نصاً وسأحوله إلى ملصق رائع!',
        'main_menu': '🎨 القائمة الرئيسية',
        'create_sticker': '✨ إنشاء ملصق',
        'create_pack': '📦 إنشاء حزمة ملصقات',
        'settings': '⚙️ الإعدادات',
        'my_projects': '📂 مشاريعي',
        'help': '❓ المساعدة',
        'send_text': '📝 أرسل النص الذي تريد تحويله إلى ملصق:',
        'choose_font': '🅰️ اختر الخط:',
        'choose_color': '🎨 اختر اللون:',
        'choose_bg': '🖼 اختر لون الخلفية:',
        'choose_size': '📏 اختر الحجم:',
        'preview': '👁 المعاينة',
        'confirm': '✅ تأكيد',
        'cancel': '❌ إلغاء',
        'pack_name': '📛 اختر اسماً للحزمة:',
        'pack_created': '✅ تم إنشاء الحزمة بنجاح!\n\nرابط الحزمة: {}',
        'pack_link': '🔗 رابط الحزمة',
        'add_more': '➕ إضافة المزيد',
        'done': '✅ انتهيت',
        'stroke': '✏️ الحواف (Stroke)',
        'shadow': '🌓 الظل',
        'gradient': '🌈 التدرج اللوني',
        'rounded': '🔘 الزوايا الدائرية',
        'error': '❌ حدث خطأ. الرجاء المحاولة مرة أخرى.',
        'banned': '⛔ أنت محظور من استخدام البوت.',
        'admin_panel': '👤 لوحة التحكم',
        'stats': '📊 الإحصائيات',
        'broadcast': '📢 إرسال جماعي',
        'ban': '🔨 حظر مستخدم',
        'unban': '🔓 فك حظر',
        'back': '🔙 رجوع',
        'text_too_long': '❌ النص طويل جداً. الحد الأقصى 100 حرف.',
        'select_lang': '🌐 اختر اللغة:',
        'language_set': '✅ تم تعيين اللغة إلى العربية',
    },
    'en': {
        'start': '✨ Welcome to <b>StickerForgeBot</b>!\n\nI\'m a professional Telegram sticker bot.\nSend me text and I\'ll turn it into a cool sticker!',
        'main_menu': '🎨 Main Menu',
        'create_sticker': '✨ Create Sticker',
        'create_pack': '📦 Create Sticker Pack',
        'settings': '⚙️ Settings',
        'my_projects': '📂 My Projects',
        'help': '❓ Help',
        'send_text': '📝 Send the text you want to convert to a sticker:',
        'choose_font': '🅰️ Choose font:',
        'choose_color': '🎨 Choose color:',
        'choose_bg': '🖼 Choose background color:',
        'choose_size': '📏 Choose size:',
        'preview': '👁 Preview',
        'confirm': '✅ Confirm',
        'cancel': '❌ Cancel',
        'pack_name': '📛 Choose a name for the pack:',
        'pack_created': '✅ Pack created successfully!\n\nPack link: {}',
        'pack_link': '🔗 Pack Link',
        'add_more': '➕ Add More',
        'done': '✅ Done',
        'stroke': '✏️ Stroke',
        'shadow': '🌓 Shadow',
        'gradient': '🌈 Gradient',
        'rounded': '🔘 Rounded Corners',
        'error': '❌ An error occurred. Please try again.',
        'banned': '⛔ You are banned from using this bot.',
        'admin_panel': '👤 Admin Panel',
        'stats': '📊 Statistics',
        'broadcast': '📢 Broadcast',
        'ban': '🔨 Ban User',
        'unban': '🔓 Unban',
        'back': '🔙 Back',
        'text_too_long': '❌ Text too long. Max 100 characters.',
        'select_lang': '🌐 Select language:',
        'language_set': '✅ Language set to English',
    }
}

def get_string(lang, key):
    return STRINGS.get(lang, STRINGS['ar']).get(key, STRINGS['ar'].get(key, key))
